#!/bin/sh

bw unlock --check > /dev/null 2>&1

if [ $? -ne 0 ]; then
    BW_SESSION="$(bw unlock --raw)" || return 1
    export BW_SESSION;
fi

bw list items --search "${1}" \
    | jq -j '.[] | [.name, .login.password]' \
    | tr -d '\n["' \
    | tr ']' '\n' \
    | tr ',' ':' \
    | sed 's/^\ \ //g' \
    | fzf --layout=reverse \
    | tail -1 \
    | tr -d '"' \
    | cut -d ':' -f 2 \
    | sed 's/^\ \ //g' \
    | cat \
    | xclip -selection clipboard \
    > /dev/null 2>&1

[ $? -ne 0 ] && return 1

return 0

